version: '3.8'

services:
  web:
    image: fredsheppard/inventory
    ports:
      - "8001:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123

volumes:
  postgres_data:
