# Use a lightweight Python image
FROM python:3.10.12

# Set working directory
WORKDIR /app

# Copy requirements.txt and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy project files
COPY . .

# Expose port for Django app
EXPOSE 8000

# Start the server
#CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
