# Generated by Django 5.0.3 on 2024-03-28 23:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('bom_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31, unique=True)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('part_number', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=31, null=True)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_description', models.CharField(blank=True, max_length=512, null=True)),
                ('purchase_unit_cost_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cost Price')),
                ('sale_unit_cost_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Selling Price')),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/parts')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=63)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BomItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bom')),
                ('part_number', models.OneToOneField(db_column='part_number', on_delete=django.db.models.deletion.CASCADE, to='app.catalogue')),
            ],
        ),
        migrations.CreateModel(
            name='BomChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bom')),
                ('part_number', models.OneToOneField(db_column='part_number', on_delete=django.db.models.deletion.CASCADE, to='app.catalogue')),
            ],
        ),
        migrations.CreateModel(
            name='CheckedOutStock',
            fields=[
                ('checked_out_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('part_number', models.ForeignKey(db_column='part_number', on_delete=django.db.models.deletion.CASCADE, to='app.catalogue')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.location')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('check_out', models.CharField(auto_created=True, default='x', editable=False, max_length=1)),
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.location')),
                ('part_number', models.ForeignKey(db_column='part_number', on_delete=django.db.models.deletion.CASCADE, to='app.catalogue')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.project')),
            ],
        ),
    ]
