# Generated by Django 5.0.3 on 2024-06-21 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_stock_project_remove_checkedoutstock_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('last_notification', models.DateTimeField(null=True)),
                ('part_number', models.ForeignKey(db_column='part_number', on_delete=django.db.models.deletion.CASCADE, to='app.catalogue')),
            ],
        ),
    ]
