# Generated by Django 5.0.3 on 2024-06-21 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tracker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tracker',
            unique_together={('part_number', 'quantity')},
        ),
    ]
