name: Build and Push Docker Image

on:
  push:
    tags:
      - v*.*.*  # Matches tags starting with "v" followed by any number (.*)

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # You can choose a different runner

    steps:
      - uses: actions/checkout@v3  # Checkout code from the repository

      - name: Login to Docker Hub
        uses: docker/login-action@v2  # Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v3  # Build and push image
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/image-name  # Replace with your details
          tags: ${{ github.ref }}, latest  # Use the pushed tag for the image
          push: true
